# -*- coding: utf-8 -*-
"""Netflix .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zoJUCnbU7NVDSbn068jpkvtbu9jr1tbp

# **Project Name**    - NETFLIX

##### **Project Type**    - EDA/Regression/Classification/Unsupervised
##### **Contribution**    - Individual/Team
##### **Team Member 1 -**
##### **Team Member 2 -**
##### **Team Member 3 -**
##### **Team Member 4 -**

# **Project Summary -**

Write the summary here within 500-600 words.

This project focuses on conducting an in-depth Exploratory Data Analysis (EDA) of a publicly available Netflix dataset, which contains metadata on over 7,700 movies and TV shows available on the platform. The primary goal is to understand the structure and distribution of content on Netflix, clean and prepare the data for analysis, and lay the foundation for clustering similar content based on genre, duration, and other attributes.

Dataset Overview
The dataset includes columns such as type (Movie or TV Show), title, director, cast, country, date_added, release_year, rating, duration, listed_in (genres), and description. After initial inspection, the dataset was found to have a number of missing values—especially in fields like director, cast, and country.

To handle these issues, we filled missing categorical data with the value "Unknown" and used the mode (most common value) for missing rating and release_year. The duration column was particularly challenging because it contained text like “93 min” or “2 Seasons.” We extracted the numeric parts into a new column (duration_int) for easier analysis and separated logic based on whether the entry was a movie or a TV show.

 Visual Analysis
Five core visualizations were generated to better understand the dataset:

1.Content Type Distribution: Movies significantly outnumber TV shows, indicating a stronger emphasis on one-off content.

2.Top Ratings: “TV-MA” and “TV-14” dominate, suggesting that Netflix's content skews toward mature and teen audiences.

3.Release Trends Over Time: A clear growth trend in the number of releases from 2000 to 2019, with a peak in 2018.

4.Movie Duration Distribution: Most movies fall within the 80-120 minute range, though outliers on both ends were identified.

5.Top Producing Countries: The United States leads, followed by India, the UK, and other major content-producing nations.

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

The problem is to analyze and cluster Netflix movies and TV shows based on metadata such as genre, duration, rating, and release year to uncover patterns in content distribution, identify user-viewing trends, and support content-based recommendations or business decisions through structured exploratory data analysis and machine learning techniques.

**Write Problem Statement Here.**

#### **Define Your Business Objective?**

Understand Content Trends: Analyze genre, duration, and rating patterns to guide future content acquisition.

Audience Targeting: Identify which content types appeal to different demographics or regions.

Content Recommendation: Enable personalized recommendations through clustering similar titles.

Optimize Content Strategy: Support data-driven decisions for regional and global content investments.

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt

"""### Dataset Loading"""

# Load Dataset
df = pd.read_csv("/content/NETFLIX MOVIES AND TV SHOWS CLUSTERING (1).csv", encoding='latin1')
df.head()

"""### Dataset First View"""

# Dataset First Look
print("First 5 Rows:")
print(df.head())

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

"""### Dataset Information"""

# Dataset Info
df.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
print("Number of Duplicate Rows:", df.duplicated().sum())

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
print("Missing Values:")
print(df.isnull().sum())

# Visualizing the missing values
plt.figure(figsize=(8, 5))
sns.heatmap(df.isnull(), cmap='viridis', cbar=False)
plt.title('Missing Values Heatmap')
plt.show()

"""### What did you know about your dataset?

Size: 7,788 entries, 12 columns

Type: Metadata of Netflix Movies and TV Shows

Key Columns:

type, title, director, cast, country

release_year, date_added, duration, rating

listed_in (genres), description

Missing Values: Mainly in director, cast, country

Data Focus: Content classification, trends, and preparation for clustering or recommendation

Goal: Understand content distribution and viewer trends for strategic insights

## ***2. Understanding Your Variables***
"""

# Dataset Columns
print("Column Names:", df.columns.tolist())

# Dataset Describe
df.describe()

"""### Variables Description

The Netflix dataset contains metadata for movies and TV shows, including title, type, director, cast, country of origin, date added to Netflix, release year, rating, duration, genre(s), and a brief description. It helps analyze content trends, viewer preferences, and supports recommendation or clustering models.

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
for column in df.columns:
    unique_values = df[column].unique()
    print(f"Unique values for {column}:")
    print(unique_values)
    print()

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Split into movies and TV shows for duration parsing
movies = df[df['type'] == 'Movie'].copy()
tv_shows = df[df['type'] == 'TV Show'].copy()

# Extract numeric durations
movies['duration_int'] = movies['duration'].str.extract('(\d+)').astype(float)
tv_shows['duration_int'] = tv_shows['duration'].str.extract('(\d+)').astype(float)

# Combine cleaned data
df_cleaned = pd.concat([movies, tv_shows])

# Define Outlier bounds
Q1 = df_cleaned['duration_int'].quantile(0.25)
Q3 = df_cleaned['duration_int'].quantile(0.75)
IQR = Q3 - Q1

# Filter Outlier
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Display Outlier
df_cleaned = df_cleaned[(df_cleaned['duration_int'] >= lower_bound) & (df_cleaned['duration_int'] <= upper_bound)]

# Handle missing values
# Fill common missing values
df['director'].fillna("Unknown", inplace=True)
df['cast'].fillna("Unknown", inplace=True)
df['country'].fillna("Unknown", inplace=True)
df['date_added'].fillna("Unknown", inplace=True)
df['rating'].fillna(df['rating'].mode()[0], inplace=True)
df['release_year'].fillna(df['release_year'].mode()[0], inplace=True)
df['listed_in'].fillna("Miscellaneous", inplace=True)
df['description'].fillna("No description", inplace=True)

# Drop rows where duration is missing
df.dropna(subset=['duration'], inplace=True)

# Fill missing 'rating' with the mode (most frequent value)
df['rating'].fillna(df['rating'].mode()[0], inplace=True)

# Fill missing 'date_added' with 'Unknown'
df_cleaned['date_added'].fillna("Unknown", inplace=True)

# Fill missing 'release_year' with the mode
df_cleaned['release_year'].fillna(df_cleaned['release_year'].mode()[0], inplace=True)

# Optional: Confirm missing values are handled
print(df_cleaned.isnull().sum())

"""### What all manipulations have you done and insights you found?

Answer Here.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1
"""

# Chart - 1 BAR CHART
 #Count of Movies vs TV Shows

import seaborn as sns
import matplotlib.pyplot as plt

sns.countplot(data=df_cleaned, x='type', palette='Set2')
plt.title("Distribution of Content Types on Netflix")
plt.xlabel("Type")
plt.ylabel("Count")
plt.show()

"""##### 1. Why did you pick the specific chart?

I chose this barchart because this bar chart is ideal for comparing categorical data. In this case, the count of the Movies vs TV shows on Netflix.

##### 2. What is/are the insight(s) found from the chart?

Movies significantly outnumber Tv shows on Netflix, with more than double the count.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, knowing that movies dominate the platform may guide content acquisition or production strategies, catering to audience preferences.

Negative Insight:
Yes, Overemphasis on movies mighr lead to underinvestment in TV shows, potentially alienating viewers who prefer eposodic content and reducing engagement duration.

#### Chart - 2 Horizontal Bar Chart
"""

# Chart - 2
 #Top 10 Most Frequent Ratings
top_ratings = df_cleaned['rating'].value_counts().nlargest(10)
sns.barplot(x=top_ratings.values, y=top_ratings.index, palette='coolwarm')
plt.title("Top 10 Content Ratings on Netflix")
plt.xlabel("Number of Shows")
plt.ylabel("Rating")
plt.show()

"""##### 1. Why did you pick the specific chart?

i chose this chart because it effectively displays categorical data and their corresponding frequencies. it makes it easy to compare the number of shows for each rating clearly, especially when category names like "TV-MA", "TV-14" are so long.

##### 2. What is/are the insight(s) found from the chart?

TV-MA nad TV-14 are the most common ratings, indicating Netflix has a large amount of marure and teen content.

Family/kids- friendly ratings like TV-Y, TV-Y7, and G have significantly fewer shows.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Positive Impact:
yes, Understanding the domain ratings helps Netflix align content strategy with audience demand. If mature content drives viewership, investing more in such categories could increase engagement and subscription.

Negative Impact:
Yes, the relatively low volume of kid-and family-friendly, a potentially profitable demographic. Neglecting this segment could limit subscriber diversity and lead to missed oppotunities in parental markets.

#### Chart - 3 The Line Plot Chart
"""

# Chart - 3
# Number of Releases Over Time
df_by_year = df_cleaned['release_year'].value_counts().sort_index()
plt.plot(df_by_year.index, df_by_year.values, marker='o')
plt.title("Content Releases Over the Years")
plt.xlabel("Year")
plt.ylabel("Number of Titles")
plt.grid(True)
plt.show()

"""##### 1. Why did you pick the specific chart?

I chose this chart because this chart is ideal for showing trends over time. It effectively visualizes how content releases on Netflix have changed year by year, highlighting growth or decline patterns clearly.

##### 2. What is/are the insight(s) found from the chart?

There is sharp increase in content starting around 2015, peaking around 2019-2020.

A decline is observed post-2020, suggesting a slowdown in new content additions.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Positive Impact:
Yes, The growth trend till 2020 indicates high content investment and expansion, showing what periods of strategy worked well. Businesses can replicate factors from those peak years to reignite growth.

Negative Impact:
Yes, The post 2020 decline may suggest production issues like: pandemic effects, budgets constraints, or shifting strategy. If the decline continues, it could reduce user engagement and subscriber retention due to fewer fresh titles.

#### Chart - 4 Histogram Chart
"""

# Chart - 4
# Movie Duration Distribution
sns.histplot(data=df_cleaned[df_cleaned['type'] == 'Movie'], x='duration_int', bins=20, kde=True)
plt.title("Distribution of Movie Durations on Netflix")

"""##### 1. Why did you pick the specific chart?

I chose this chart because it is ideal for showing the distribution of continuous variables like movie duration ranges effectively.

##### 2. What is/are the insight(s) found from the chart?

Most Netflix movies are between 75 to 120 minutes long, with the peak around 90 minutes.

Very few movies are under 50 minutes or over 150 minutes.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Positive Impact: Yes Understanding optimal duration helps Netflix produce content that aligns with user preferences. A majority preferences for 90 minutes movies indicates that the ideal length for engagement and completion

Negative Impact:
Yes, The low number of shorts or very long movies suggests Netflix might be missing out on audiences who prefer quick content or long-form storytelling. This gap could be exploited competitors.

#### Chart - 5 Horizontal Bar Chart
"""

# Chart - 5
# Top 10 Producing Countries
top_countries = df_cleaned['country'].value_counts().nlargest(10)
sns.barplot(x=top_countries.values, y=top_countries.index, palette='viridis')
plt.title("Top 10 Producing Countries on Netflix")

"""##### 1. Why did you pick the specific chart?

I chose this chart because it is perfect for comparing with long names like country names, making it easy to read and compare production volume across countries.

##### 2. What is/are the insight(s) found from the chart?

The United States is the top producer on Netflix by large margin.

India, Uk, and Japan follow as significant contributors.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Positive Impact:
Yes, This helps Netflix understand where most content comes from and where to invest more in local productions, growing partnerships in India and South Korea can expand Netflix's global market.

Negative Imapct:
Yes, The presence of high Unknown category suggest poor metadata quality. This can hinder regional analytics, recommendation systems, and localization strategies, leading to a suboptimal user experience and missed targeting opportunities.

Chart- 6

##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 7
"""

# Chart - 7 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 8
"""

# Chart - 8 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 9
"""

# Chart - 9 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 10
"""

# Chart - 10 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 11
"""

# Chart - 11 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 12
"""

# Chart - 12 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 13
"""

# Chart - 13 visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Answer Here

#### Chart - 14 - Correlation Heatmap
"""

# Correlation Heatmap visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

#### Chart - 15 - Pair Plot
"""

# Pair Plot visualization code

"""##### 1. Why did you pick the specific chart?

Answer Here.

##### 2. What is/are the insight(s) found from the chart?

Answer Here

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?

To achieve the business objectives, I suggest the client:

1.Leverage Clustering to group similar content for personalized recommendations.

2.Analyze Genre & Country Trends to guide regional content acquisition.

3.Optimize Content Mix by focusing on high-performing durations and ratings.

4.Target Mature Audiences with curated TV-MA and TV-14 content.

5.Use Viewer Trend Insights to plan release schedules and marketing campaigns.

# **Conclusion**

This EDA project provides a solid understanding of Netflix’s content landscape. By cleaning and visualizing the data, we now have meaningful insights into how content is distributed by type, duration, geography, and rating. The cleaned dataset is ready for advanced tasks such as clustering or recommendation system modeling based on similarities in genre, duration, and production metadata.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""



